import sys

# generates cdef string from each file in 'filenames'
def readdef(filenames):
    str = ''

    for filename in filenames:
        with open(filename, 'r') as file:
            str = str + '    /* ' + filename + ' */\n'

            in_script = 0
            for line in file.readlines():
                if line.find('script_begin') >= 0:
                    in_script = in_script + 1
                elif line.find('script_end') >= 0 and in_script > 0:
                    in_script = in_script - 1
                elif in_script > 0 or line.find('script_export') >= 0:
                    line = line[:line.find('\n')] # remove '\n' if there's one
                    if line == '':
                        str = str + '\n'
                    else:
                        str = '%s    "%s\\n"\n' % (str, line)

    return str

# write out with a nice header

fmt = """
/* 
 * C interface visible from Lua
 * 
 * automatically generated by gen_cgame_ffi.lua from 'script_begin/script_end'
 * blocks and 'script_export' lines
 *
 * pass the string 'cgame_ffi' to ffi.cdef(...) in LuaJIT
 */

static const char cgame_ffi[] =
%s
    ;
"""

s = readdef(sys.argv[1:])
with open('cgame_ffi.h', 'w') as file:
    file.write(fmt % (s))

