#include "input.h"

#include "glew_glfw.h"
#include "game.h"

static int _keycode_to_glfw(KeyCode key);
static KeyCode _glfw_to_keycode(int key); /* XXX: not implemented yet */

bool input_key_down(KeyCode key)
{
    return glfwGetKey(game_window, _keycode_to_glfw(key)) == GLFW_PRESS;
}

static int _keycode_to_glfw(KeyCode key)
{
    static const int arr[KC_NUM_KEYCODES] =
        {
            [KC_UNKNOWN] = GLFW_KEY_UNKNOWN,

            [KC_SPACE] = GLFW_KEY_SPACE,
            [KC_0] = GLFW_KEY_0,
            [KC_1] = GLFW_KEY_1,
            [KC_2] = GLFW_KEY_2,
            [KC_3] = GLFW_KEY_3,
            [KC_4] = GLFW_KEY_4,
            [KC_5] = GLFW_KEY_5,
            [KC_6] = GLFW_KEY_6,
            [KC_7] = GLFW_KEY_7,
            [KC_8] = GLFW_KEY_8,
            [KC_9] = GLFW_KEY_9,
            [KC_A] = GLFW_KEY_A,
            [KC_B] = GLFW_KEY_B,
            [KC_C] = GLFW_KEY_C,
            [KC_D] = GLFW_KEY_D,
            [KC_E] = GLFW_KEY_E,
            [KC_F] = GLFW_KEY_F,
            [KC_G] = GLFW_KEY_G,
            [KC_H] = GLFW_KEY_H,
            [KC_I] = GLFW_KEY_I,
            [KC_J] = GLFW_KEY_J,
            [KC_K] = GLFW_KEY_K,
            [KC_L] = GLFW_KEY_L,
            [KC_M] = GLFW_KEY_M,
            [KC_N] = GLFW_KEY_N,
            [KC_O] = GLFW_KEY_O,
            [KC_P] = GLFW_KEY_P,
            [KC_Q] = GLFW_KEY_Q,
            [KC_R] = GLFW_KEY_R,
            [KC_S] = GLFW_KEY_S,
            [KC_T] = GLFW_KEY_T,
            [KC_U] = GLFW_KEY_U,
            [KC_V] = GLFW_KEY_V,
            [KC_W] = GLFW_KEY_W,
            [KC_X] = GLFW_KEY_X,
            [KC_Y] = GLFW_KEY_Y,
            [KC_Z] = GLFW_KEY_Z,

            [KC_ESCAPE] = GLFW_KEY_ESCAPE,
            [KC_ENTER] = GLFW_KEY_ENTER,
            [KC_TAB] = GLFW_KEY_TAB,
            [KC_BACKSPACE] = GLFW_KEY_BACKSPACE,
            [KC_INSERT] = GLFW_KEY_INSERT,
            [KC_DELETE] = GLFW_KEY_DELETE,
            [KC_RIGHT] = GLFW_KEY_RIGHT,
            [KC_LEFT] = GLFW_KEY_LEFT,
            [KC_DOWN] = GLFW_KEY_DOWN,
            [KC_UP] = GLFW_KEY_UP,
            [KC_PAGE_UP] = GLFW_KEY_PAGE_UP,
            [KC_PAGE_DOWN] = GLFW_KEY_PAGE_DOWN,
            [KC_HOME] = GLFW_KEY_HOME,
            [KC_END] = GLFW_KEY_END,
            [KC_CAPS_LOCK] = GLFW_KEY_CAPS_LOCK,
            [KC_SCROLL_LOCK] = GLFW_KEY_SCROLL_LOCK,
            [KC_NUM_LOCK] = GLFW_KEY_NUM_LOCK,
            [KC_PRINT_SCREEN] = GLFW_KEY_PRINT_SCREEN,
            [KC_PAUSE] = GLFW_KEY_PAUSE,
            [KC_F1] = GLFW_KEY_F1,
            [KC_F2] = GLFW_KEY_F2,
            [KC_F3] = GLFW_KEY_F3,
            [KC_F4] = GLFW_KEY_F4,
            [KC_F5] = GLFW_KEY_F5,
            [KC_F6] = GLFW_KEY_F6,
            [KC_F7] = GLFW_KEY_F7,
            [KC_F8] = GLFW_KEY_F8,
            [KC_F9] = GLFW_KEY_F9,
            [KC_F10] = GLFW_KEY_F10,
            [KC_F11] = GLFW_KEY_F11,
            [KC_F12] = GLFW_KEY_F12,
            [KC_F13] = GLFW_KEY_F13,
            [KC_F14] = GLFW_KEY_F14,
            [KC_F15] = GLFW_KEY_F15,
            [KC_F16] = GLFW_KEY_F16,
            [KC_F17] = GLFW_KEY_F17,
            [KC_F18] = GLFW_KEY_F18,
            [KC_F19] = GLFW_KEY_F19,
            [KC_F20] = GLFW_KEY_F20,
            [KC_F21] = GLFW_KEY_F21,
            [KC_F22] = GLFW_KEY_F22,
            [KC_F23] = GLFW_KEY_F23,
            [KC_F24] = GLFW_KEY_F24,
            [KC_F25] = GLFW_KEY_F25,
            [KC_KP_0] = GLFW_KEY_KP_0,
            [KC_KP_1] = GLFW_KEY_KP_1,
            [KC_KP_2] = GLFW_KEY_KP_2,
            [KC_KP_3] = GLFW_KEY_KP_3,
            [KC_KP_4] = GLFW_KEY_KP_4,
            [KC_KP_5] = GLFW_KEY_KP_5,
            [KC_KP_6] = GLFW_KEY_KP_6,
            [KC_KP_7] = GLFW_KEY_KP_7,
            [KC_KP_8] = GLFW_KEY_KP_8,
            [KC_KP_9] = GLFW_KEY_KP_9,
            [KC_KP_DECIMAL] = GLFW_KEY_KP_DECIMAL,
            [KC_KP_DIVIDE] = GLFW_KEY_KP_DIVIDE,
            [KC_KP_MULTIPLY] = GLFW_KEY_KP_MULTIPLY,
            [KC_KP_SUBTRACT] = GLFW_KEY_KP_SUBTRACT,
            [KC_KP_ADD] = GLFW_KEY_KP_ADD,
            [KC_KP_ENTER] = GLFW_KEY_KP_ENTER,
            [KC_KP_EQUAL] = GLFW_KEY_KP_EQUAL,
            [KC_LEFT_SHIFT] = GLFW_KEY_LEFT_SHIFT,
            [KC_LEFT_CONTROL] = GLFW_KEY_LEFT_CONTROL,
            [KC_LEFT_ALT] = GLFW_KEY_LEFT_ALT,
            [KC_LEFT_SUPER] = GLFW_KEY_LEFT_SUPER,
            [KC_RIGHT_SHIFT] = GLFW_KEY_RIGHT_SHIFT,
            [KC_RIGHT_CONTROL] = GLFW_KEY_RIGHT_CONTROL,
            [KC_RIGHT_ALT] = GLFW_KEY_RIGHT_ALT,
            [KC_RIGHT_SUPER] = GLFW_KEY_RIGHT_SUPER,
            [KC_MENU] = GLFW_KEY_MENU,
        };

    return arr[key];
}

